### ISSUE TITLE
The recovery in TS50 and t500 Dataset

### ISSUE THREAD

**Issue by wacharlin** [ykiiiiii/GraDe_IF#8]
Hi, could you release the ckpt and config about the TS50 and T500 dataset?  because I follow the setting in paper that `hidden_size` boost to 256, the recoveries of  the two datasets are reduced by about 5 percentage points. Maybe `the mean_attr.pt` is not suitable for these dataset?  I am confused.. so hope to receive reply. 

thanks!

**Comment by llllly26** [comment]
Hi @ykiiiiii , I have a follow-up problem. 
(1) I followed the paper to process TS50/T500 dataset,  and the final recovery is lower about 3% than paper's. 
(2) In paper,The best performance is achieved when skipping a single step, but when using released weight [[UNIFORM_3M_small.pt](https://github.com/ykiiiiii/GraDe_IF/blob/main/diffusion/results/weight/UNIFORM_3M_small.pt)] and [BLOSUM_3M_small.pt](https://github.com/ykiiiiii/GraDe_IF/blob/main/diffusion/results/weight/BLOSUM_3M_small.pt),  and i set the step=1, the recovery is lower, and about 20%. 
I don't know which step went wrong with me, I hope to receive your help.
thanks!

**Comment by 123730** [comment]
loss = diffusion_model(input_graph)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhangshuai/mmy/GraDe_IF-main/diffusion/gradeif.py", line 452, in forward
    pred_X = self.model(noise_data,t_int) #have parameter
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhangshuai/mmy/GraDe_IF-main/diffusion/gradeif.py", line 129, in forward
    h,edge_attr = layer(x, edge_index, edge_attr, batch) #[N,hidden_dim]
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhangshuai/miniconda3/envs/protein/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhangshuai/mmy/GraDe_IF-main/diffusion/model/egnn_pytorch/egnn_pytorch_geometric.py", line 250, in forward
    hidden_out, coors_out, *_ = self.propagate(edge_index, x=feats, edge_attr=edge_attr_feats,
ValueError: too many values to unpack (expected 3)
how to deal with this problem please
